
const order_Data = [
    {
        "ID": 34794,
        "Code": "D2505347",
        "Company": "PTT",
        "DateArrival": "2025-05-15T04:00:00",
        "Carrier": "THAI SPECIAL GAS CO., LTD",
        "FontLicense": "54-1561",
        "RearLicense": "69-0769 (PRV)",
        "Driver1": "นายธเนศ   ุบุตรศาสตร์",
        "Driver2": "นายจักรกฤช โพธิ์ผลิ",
        "Driver3": "นายปราโมทย์  ทองสิทธิ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747209787",
        "ApproveID": 961,
        "ApproveName": "TSG LNG",
        "DestinationID": 387,
        "DestinationName": "I STAINLESS STEEL CO.,LTD",
        "TareWeight": "28470",
        "MaxWeight": "20988",
        "VehicleName": "",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34793,
        "Code": "D2505346",
        "Company": "PTT",
        "DateArrival": "2025-05-15T10:00:00",
        "Carrier": "THAI SPECIAL GAS CO., LTD",
        "FontLicense": "54-1564",
        "RearLicense": "54-1563",
        "Driver1": "นายมานะ อ่วมเจริญ",
        "Driver2": "นายปราโมทย์  ทองสิทธิ",
        "Driver3": "นายสุริยัณห์  พันพนม",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747208647",
        "ApproveID": 961,
        "ApproveName": "TSG LNG",
        "DestinationID": 385,
        "DestinationName": "เดลทัล เทคโนโลยี (ไทยแลนด์) จำกัด",
        "TareWeight": "30650",
        "MaxWeight": "19850",
        "VehicleName": "THAI SPECIAL GAS",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34790,
        "Code": "D2505343",
        "Company": "PTT",
        "DateArrival": "2025-05-15T17:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-6512",
        "RearLicense": "67-6252",
        "Driver1": "Mr. Witsanukon Sonwai",
        "Driver2": "Mr. Artit Konseela",
        "Driver3": "Mr. Roengsak Janphet",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747198884",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 396,
        "DestinationName": "MULTI-FINELINE ELECTRONICS (THAILAND)",
        "TareWeight": "31500",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG ",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34789,
        "Code": "D2505342",
        "Company": "PTT",
        "DateArrival": "2025-05-14T13:00:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "71-0901 นนทบุรี",
        "RearLicense": "69-7970 กรุงเทพมหานคร",
        "Driver1": "วีระศักดิ์ จันรุณ",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747198662",
        "ApproveID": 889,
        "ApproveName": "Biggas LNG",
        "DestinationID": 128,
        "DestinationName": "บริษัท ไซม์ ดาร์บี้ ออยส์ มรกต จำกัด (มหาชน) (1)",
        "TareWeight": "26760",
        "MaxWeight": "19800",
        "VehicleName": "",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34788,
        "Code": "D2505341",
        "Company": "PTT",
        "DateArrival": "2025-05-14T16:00:00",
        "Carrier": "BIG",
        "FontLicense": "403 83-1985",
        "RearLicense": "5002 83-4329",
        "Driver1": " สมพร   จิลานนท์",
        "Driver2": " สัมพันธ์   อู่คชสาร",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747196971",
        "ApproveID": 968,
        "ApproveName": "ประเสริฐ   ดีเกษม",
        "DestinationID": 106,
        "DestinationName": "Western Power ( Thailand ) Co.,Ltd.",
        "TareWeight": "23350",
        "MaxWeight": "17000",
        "VehicleName": "BIG",
        "IsFullTank": true,
        "RegulationWeight": 45000.0
    },
    {
        "ID": 34787,
        "Code": "D2505340",
        "Company": "PTT",
        "DateArrival": "2025-05-14T17:00:00",
        "Carrier": "KIATTANA (LNG สาขาระยอง)",
        "FontLicense": "70-4024 (KTT สาขาระยอง2)",
        "RearLicense": "70-4080 (KTT สาขาระยอง2)",
        "Driver1": "ราวี จันทรโครต",
        "Driver2": "นิรุติ   เกลี้ยงดี",
        "Driver3": "สิทธิพงษ์ วงษาลุน",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747192777",
        "ApproveID": 985,
        "ApproveName": "Arnont Sreeragsar",
        "DestinationID": 313,
        "DestinationName": "บริษัท จุน จี่ แมททีเรียล เทคโนโลยี  จำกัด",
        "TareWeight": "26200",
        "MaxWeight": "17000",
        "VehicleName": "KTT",
        "IsFullTank": true,
        "RegulationWeight": 45000.0
    },
    {
        "ID": 34786,
        "Code": "D2505339",
        "Company": "PTT",
        "DateArrival": "2025-05-15T18:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-6183.",
        "RearLicense": "67-6186.",
        "Driver1": "Mr.Jakkrapong Suksawaeng",
        "Driver2": "Mr. Artit Konseela",
        "Driver3": "Mr. Aphichai Rattanasensri",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747192231",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 44,
        "DestinationName": "Vossen Amata City Rayong",
        "TareWeight": "30560",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34785,
        "Code": "D2505338",
        "Company": "PTT",
        "DateArrival": "2025-05-15T11:30:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-6512",
        "RearLicense": "67-6252",
        "Driver1": "Mr. Chan  Promnoi",
        "Driver2": "Mr. Chairoongrueng Phloenphookhieo",
        "Driver3": "Mr. Sirisak Sa-Im",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747192168",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 81,
        "DestinationName": "IP Natural Product",
        "TareWeight": "31500",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG ",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34784,
        "Code": "D2505337",
        "Company": "PTT",
        "DateArrival": "2025-05-15T20:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-9607",
        "RearLicense": "53-1217",
        "Driver1": "Mr. Surapong Suwanyen",
        "Driver2": "Mr. Witsanukon Sonwai",
        "Driver3": "Mr. Artit Konseela",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747192123",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 25,
        "DestinationName": "Marspetcare Chonburi",
        "TareWeight": "26860",
        "MaxWeight": "17300",
        "VehicleName": "IBCLNG",
        "IsFullTank": true,
        "RegulationWeight": 45000.0
    },
    {
        "ID": 34783,
        "Code": "D2505336",
        "Company": "PTT",
        "DateArrival": "2025-05-15T14:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "53-1829 FRONT",
        "RearLicense": "53-1829 REAR",
        "Driver1": "Mr.Jakkrapong Suksawaeng",
        "Driver2": "Mr. Witsanukon Sonwai",
        "Driver3": "MR.Somchay  Phanmart",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747192016",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 335,
        "DestinationName": "Thai Nasmsiri Intertex Co,.Ltd",
        "TareWeight": "16300",
        "MaxWeight": "8000",
        "VehicleName": "IBCLNG",
        "IsFullTank": true,
        "RegulationWeight": 25000.0
    },
    {
        "ID": 34782,
        "Code": "D2505335",
        "Company": "PTT",
        "DateArrival": "2025-05-14T15:00:00",
        "Carrier": "บริษัท เกียรติธนาขนส่ง จำกัด",
        "FontLicense": "70-6420",
        "RearLicense": "70-7042",
        "Driver1": "นายนิรุติ เกลี้ยงดี",
        "Driver2": "นายณัฐพงค์ ประดิษฐ์สาร",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747191938",
        "ApproveID": 961,
        "ApproveName": "TSG LNG",
        "DestinationID": 288,
        "DestinationName": "BOYUAN METAL (THAILAND) CO., LTD",
        "TareWeight": "28610",
        "MaxWeight": "20457",
        "VehicleName": "",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34781,
        "Code": "D2505334",
        "Company": "PTT",
        "DateArrival": "2025-05-14T20:00:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "700-2187 กรุงเทพมหานคร",
        "RearLicense": "700-2077 กรุงเทพมหานคร",
        "Driver1": "อนุชา   อรัญยะเวช",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747191176",
        "ApproveID": 889,
        "ApproveName": "Biggas LNG",
        "DestinationID": 344,
        "DestinationName": "บริษัท บีวายดี ออโต้ (ประเทศไทย) จำกัด",
        "TareWeight": "28690",
        "MaxWeight": "20400",
        "VehicleName": "",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34779,
        "Code": "D2505332",
        "Company": "PTT",
        "DateArrival": "2025-05-15T15:00:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "71-0901 นนทบุรี",
        "RearLicense": "69-7970 กรุงเทพมหานคร",
        "Driver1": "วีระศักดิ์ จันรุณ",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747191125",
        "ApproveID": 889,
        "ApproveName": "Biggas LNG",
        "DestinationID": 128,
        "DestinationName": "บริษัท ไซม์ ดาร์บี้ ออยส์ มรกต จำกัด (มหาชน) (1)",
        "TareWeight": "26760",
        "MaxWeight": "19800",
        "VehicleName": "",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34778,
        "Code": "D2505331",
        "Company": "PTT",
        "DateArrival": "2025-05-14T18:00:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "68-1730 กรุงเทพมหานคร",
        "RearLicense": "68-1730 กรุงเทพมหานคร (หางลาก)",
        "Driver1": "พิบูล   สามพ่วงบุญ",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747191090",
        "ApproveID": 889,
        "ApproveName": "Biggas LNG",
        "DestinationID": 325,
        "DestinationName": "บริษัท ธนบุรีประกอบรถยนต์ จำกัด(โรงงาน2)",
        "TareWeight": "15700",
        "MaxWeight": "9200",
        "VehicleName": "Biggas",
        "IsFullTank": true,
        "RegulationWeight": 25000.0
    },
    {
        "ID": 34776,
        "Code": "D2505329",
        "Company": "PTT",
        "DateArrival": "2025-05-14T14:00:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "70-9791 นนทบุรี",
        "RearLicense": "70-9899 นนทบุรี",
        "Driver1": "นายวิวัฒน์ ทนวิรักษ์",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747191019",
        "ApproveID": 889,
        "ApproveName": "Biggas LNG",
        "DestinationID": 123,
        "DestinationName": "บริษัท ทีเอ็มเอ็ม ฟู้ด (ไทยแลนด์) จำกัด (1)",
        "TareWeight": "25190",
        "MaxWeight": "18200",
        "VehicleName": "BIGGAS",
        "IsFullTank": true,
        "RegulationWeight": 45000.0
    },
    {
        "ID": 34772,
        "Code": "D2505325",
        "Company": "PTT",
        "DateArrival": "2025-05-14T00:30:00",
        "Carrier": "CARRIER-TEST1",
        "FontLicense": "71-0584 นนทบุรี",
        "RearLicense": "70-9899 นนทบุรี",
        "Driver1": "วีระศักดิ์ จันรุณ",
        "Driver2": " ",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747132093",
        "ApproveID": 889,
        "ApproveName": "BiggasLNG",
        "DestinationID": 328,
        "DestinationName": "บริษัท เค-99 พลาสเทค จำกัด",
        "TareWeight": "25350",
        "MaxWeight": "18200",
        "VehicleName": "BIGGAS",
        "IsFullTank": true,
        "RegulationWeight": 45000.0
    },
    {
        "ID": 34767,
        "Code": "D2505320",
        "Company": "PTT",
        "DateArrival": "2025-05-15T08:00:00",
        "Carrier": "ลัคกี้แคร์ริเออร์",
        "FontLicense": "67-8410 หัว",
        "RearLicense": "67-8410 หาง",
        "Driver1": "พรชัย จันทร์ทอง",
        "Driver2": "นายสมร เขื่อนมั่น",
        "Driver3": " ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747123930",
        "ApproveID": 976,
        "ApproveName": "ปทัตตา สุธรรมานนท์",
        "DestinationID": 138,
        "DestinationName": "บริษัท ลัคกี้แคร์ริเออร์ จำกัด(1)",
        "TareWeight": "15600",
        "MaxWeight": "9061",
        "VehicleName": "ลัคกี้ แคร์ริเออร์ จำกัด.",
        "IsFullTank": true,
        "RegulationWeight": 25000.0
    },
    {
        "ID": 34766,
        "Code": "D2505319",
        "Company": "PTT",
        "DateArrival": "2025-05-14T14:00:00",
        "Carrier": "THAI SPECIAL GAS CO., LTD",
        "FontLicense": "54-1635 (10W)",
        "RearLicense": "54-1635 (10W)",
        "Driver1": "นายพลายชุมพล สงสุข",
        "Driver2": "นายสุริยัณห์  พันพนม",
        "Driver3": "นายปราโมทย์  ทองสิทธิ",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747119759",
        "ApproveID": 961,
        "ApproveName": "TSG LNG",
        "DestinationID": 284,
        "DestinationName": "Procter and Gamble Manufacturing (Thailand) Co., Ltd",
        "TareWeight": "16100",
        "MaxWeight": "6000",
        "VehicleName": "TSG",
        "IsFullTank": true,
        "RegulationWeight": 25000.0
    },
    {
        "ID": 34765,
        "Code": "D2505318",
        "Company": "PTT",
        "DateArrival": "2025-05-14T12:00:00",
        "Carrier": "THAI SPECIAL GAS CO., LTD",
        "FontLicense": "54-1564",
        "RearLicense": "54-1563",
        "Driver1": "นายมานะ อ่วมเจริญ",
        "Driver2": "นายปราโมทย์  ทองสิทธิ",
        "Driver3": "นายธเนศ   ุบุตรศาสตร์",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747119650",
        "ApproveID": 961,
        "ApproveName": "TSG LNG",
        "DestinationID": 161,
        "DestinationName": "New Thai Wheel Manufacturing Co.,Ltd. (Fac.2)",
        "TareWeight": "30650",
        "MaxWeight": "19850",
        "VehicleName": "THAI SPECIAL GAS",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34762,
        "Code": "D2505315",
        "Company": "PTT",
        "DateArrival": "2025-05-14T17:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-9606",
        "RearLicense": "67-6243",
        "Driver1": "Mr. Aphichai Rattanasensri",
        "Driver2": "Mr. Chan  Promnoi",
        "Driver3": "Mr. Sirisak Sa-Im",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747119012",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 382,
        "DestinationName": "High Precision Tube(Thailand) Co.,Ltd",
        "TareWeight": "30470",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34761,
        "Code": "D2505314",
        "Company": "PTT",
        "DateArrival": "2025-05-14T17:20:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-6183.",
        "RearLicense": "67-6186.",
        "Driver1": "Mr.Suthep Thiyo",
        "Driver2": "Somphon Somphongphueng",
        "Driver3": "Mr. Artit Konseela",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747117014",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 44,
        "DestinationName": "Vossen Amata City Rayong",
        "TareWeight": "30560",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    },
    {
        "ID": 34731,
        "Code": "D2505284",
        "Company": "PTT",
        "DateArrival": "2025-05-14T01:00:00",
        "Carrier": "IBCLNG",
        "FontLicense": "67-6512",
        "RearLicense": "67-6252",
        "Driver1": "Mr. Kun  Nonsiri",
        "Driver2": "Mr.Jakkrapong Suksawaeng",
        "Driver3": "Somphon Somphongphueng",
        "Product": "LNG",
        "Quantity": "0",
        "CreateDate": "1747009664",
        "ApproveID": 899,
        "ApproveName": "Sayan Juisom",
        "DestinationID": 298,
        "DestinationName": "CHONGFA COMPANY LIMITED",
        "TareWeight": "31500",
        "MaxWeight": "19500",
        "VehicleName": "IBCLNG ",
        "IsFullTank": true,
        "RegulationWeight": 50500.0
    }
]
// export default order_Data;

const bay_Status_Data = [
    {
        id: 'A',
        status: 'โหลดเสร็จสิ้น',
        weight: 17221,
        loading: 17221,
        maxLoading: 17221, 
        timeLoading: '10/10 นาที',
        state: 'finished ',
        carrier: 'IBCLNG',
        verified: true,
        frontlicense: '54-1564',
        rearlicense: '54-1563',
        queuenumber: 1,
        color: 'from-emerald-400 to-emerald-600',
        bgColor: 'bg-emerald-50',
        bgLeft: '#34d399',
        bgRight: '#059669',
        textColor: 'text-emerald-800',
        icon: '✓'
    },
    {
        id: 'B',
        status: 'กำลังโหลด',
        weight: 7611,
        loading: 7611,
        maxLoading: 17221, 
        timeLoading: '5/10 นาที',
        state: 'loading',
        carrier: 'THAI SPECIAL GAS CO., LTD',
        verified: true,
        frontlicense: '67-6512',
        rearlicense: '67-6252',
        queuenumber: 2,
        color: 'from-amber-400 to-orange-500',
        bgColor: 'bg-amber-50',
        bgLeft: '#fbbf24',
        bgRight: '#f97316',
        textColor: 'text-amber-800',
        icon: '⟳'
    },
    {
        id: 'C',
        status: 'อยู่ระหว่างซ่อมบำรุง',
        weight: 0,
        loading: null,
        maxLoading: 17221, 
        timeLoading: '',
        state: 'maintenance',
        carrier: '',
        verified: true,
        frontlicense: '403 83-1985',
        rearlicense: '5002 83-4329',
        queuenumber: 3,
        color: 'from-red-400 to-red-600',
        bgColor: 'bg-red-50',
        bgLeft: '#e0e0e0',
        bgRight: '#e0e0e0',
        textColor: 'text-red-800',
        icon: '⚠'
    },
    {
        id: 'D',
        status: 'Dry Run',
        weight: 0,
        loading: 0,
        maxLoading: 17221, 
        timeLoading: '',
        state: 'dry-run',
        carrier: 'CARRIER-TEST1',
        verified: true,
        frontlicense: '67-9607',
        rearlicense: '53-1217',
        queuenumber: 4,
        color: 'from-blue-400 to-blue-600',
        bgColor: 'bg-blue-50',
        bgLeft: '#e0e0e0',
        bgRight: '#e0e0e0',
        textColor: 'text-blue-800',
        icon: '○'
    },
    {
        id: 'E',
        status: 'ว่าง',
        weight: 0,
        loading: null,
        maxLoading: 17221, 
        timeLoading: '',
        state: 'free',
        carrier: '',
        verified: false,
        frontlicense: '',
        rearlicense: '',
        queuenumber: null,
        color: 'from-slate-400 to-slate-600',
        bgColor: 'bg-white',
        bgLeft: '#e0e0e0',
        bgRight: '#e0e0e0',
        textColor: 'text-slate-800',
        icon: '⚠'
    },
    {
        id: 'F',
        status: 'เรียกคิว',
        weight: 0,
        loading: 5000,
        maxLoading: 17221, 
        timeLoading: '',
        state: 'pending',
        verified: false,
        frontlicense: '67-9607',
        rearlicense: '53-1217',
        queuenumber: 6,
        carrier: 'CARRIER-TEST1',
        color: 'from-slate-400 to-slate-600',
        bgColor: 'bg-white',
        bgLeft: '#e0e0e0',
        bgRight: '#e0e0e0',
        textColor: 'text-slate-800',
        icon: '⚠'
    }
];
export { bay_Status_Data, order_Data };